[package]
name = "lu-formats-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
serde_yaml = "0.9.16"
serde = "1.0.152"
quote = "1.0.23"
kaitai-struct-types = { path = "./kaitai-struct-types" }
heck = "0.4.0"

[workspace]
members = [".", "kaitai-struct-types"]
