[package]
name = "kaitai-codegen-quote"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.152"
quote = "1.0.23"
heck = "0.4.0"
kaitai-struct-types = { path = "../kaitai-struct-types" }
proc-macro2 = "1.0.49"
